---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: rbudarin/nginx:latest  # Явно указать тег
        ports:
        - containerPort: 80
        imagePullPolicy: Always  # Добавить политику обновления образов