
name: Build and Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*' ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          rbudarin/nginx:latest
          rbudarin/nginx:${{ github.ref_name }}

  deploy:
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/')  # Запускаем деплой только для тегов
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup kubeconfig
      run: echo '${{ secrets.KUBECONFIG_FILE }}' > kubeconfig
      
    - name: Install Kubernetes CLI
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
    
    - name: Deploy using manifests
      run: |
        export KUBECONFIG=kubeconfig
        # Подставляем тег образа в манифест
        sed -i "s|rbudarin/nginx:.*|rbudarin/nginx:${{ github.ref_name }}|" deployment.yaml
          
        # Применяем манифесты
        kubectl apply -f deployment.yaml -f service.yaml
  